Repository nvbach91/4IZ268-2020-2021-ZS, pull requests merged in 2021-01, with the labels that each got.

#194 prod10-sp2
  www/prod10/sp2/assets/css/style.css
  www/prod10/sp2/assets/js/main.js
  www/prod10/sp2/index.html
Labels: Good PR

#215 valm08-sp2
  www/valm08/sp2/assets/css/main.css
  www/valm08/sp2/assets/img/favicon.ico
  www/valm08/sp2/assets/img/logo.png
  www/valm08/sp2/assets/js/main.js
  www/valm08/sp2/index.html
Labels: Good PR

#204 zofm00-sp2
  www/zofm00/sp2/css/index.css
  www/zofm00/sp2/images/background.jpg
  www/zofm00/sp2/images/bin_closed.png
  www/zofm00/sp2/images/bin_open.png
  www/zofm00/sp2/images/favicon.ico
  www/zofm00/sp2/index.html
  www/zofm00/sp2/js/jquery-3.5.1.min.js
  www/zofm00/sp2/js/main.js
Labels: Good PR

#193 seip00-sp2
  www/seip00/sp2/css/styles.css
  www/seip00/sp2/icons/01d.png
  www/seip00/sp2/icons/01n.png
  www/seip00/sp2/icons/02d.png
  www/seip00/sp2/icons/02n.png
  www/seip00/sp2/icons/03d.png
  www/seip00/sp2/icons/03n.png
  www/seip00/sp2/icons/04d.png
  www/seip00/sp2/icons/04n.png
  www/seip00/sp2/icons/09d.png
  www/seip00/sp2/icons/09n.png
  www/seip00/sp2/icons/10d.png
  www/seip00/sp2/icons/10n.png
  www/seip00/sp2/icons/11d.png
  www/seip00/sp2/icons/11n.png
  www/seip00/sp2/icons/13d.png
  www/seip00/sp2/icons/13n.png
  www/seip00/sp2/icons/50d.png
  www/seip00/sp2/icons/50n.png
  www/seip00/sp2/icons/unknown.png
  www/seip00/sp2/images/city_background.jpg
  www/seip00/sp2/images/favicon.ico
  www/seip00/sp2/index.html
  www/seip00/sp2/js/main.js
Labels: Good PR, Jedi knight

#191 stey04 sp2
  www/stey04/sp2/assets/iss.png
  www/stey04/sp2/assets/iss2.png
  www/stey04/sp2/css/main.css
  www/stey04/sp2/index.html
  www/stey04/sp2/js/main.js
Labels: Good PR

#182 vavl03-sp2
  www/vavl03/sp2/css/styles.css
  www/vavl03/sp2/images/dota-2.png
  www/vavl03/sp2/images/dota_logo.png
  www/vavl03/sp2/index.html
  www/vavl03/sp2/js/countUp.min.js
  www/vavl03/sp2/js/main.js
  www/vavl03/sp2/styles.css
Labels: Good PR, Sith lord

#176 horl13-sp2
  www/horl13/sp2/css/style.css
  www/horl13/sp2/favicon.ico
  www/horl13/sp2/index.html
  www/horl13/sp2/js/script.js
Labels: Good PR, Sith lord

#181 jedv00-sp2
  www/jedv00/sp2/css/style.css
  www/jedv00/sp2/index.html
  www/jedv00/sp2/js/script.js
Labels: Good PR, Jedi master

#213 ngut37-sp2
  www/ngut37/sp02/.env-example
  www/ngut37/sp02/.gitignore
  www/ngut37/sp02/package.json
  www/ngut37/sp02/public/index.html
  www/ngut37/sp02/src/app.tsx
  www/ngut37/sp02/src/components/about/about.scss
  www/ngut37/sp02/src/components/about/about.tsx
  www/ngut37/sp02/src/components/add-form/form.scss
  www/ngut37/sp02/src/components/add-form/form.tsx
  www/ngut37/sp02/src/components/footer/footer.scss
  www/ngut37/sp02/src/components/footer/footer.tsx
  www/ngut37/sp02/src/components/links-list/links-list..tsx
  www/ngut37/sp02/src/components/links-list/links-list.scss
  www/ngut37/sp02/src/components/links-list/links-table/list-item.tsx
  www/ngut37/sp02/src/components/links-list/links-table/list-table.scss
  www/ngut37/sp02/src/components/links-list/links-table/list-table.tsx
  www/ngut37/sp02/src/components/navbar/navbar.scss
  www/ngut37/sp02/src/components/navbar/navbar.tsx
  www/ngut37/sp02/src/index.tsx
  www/ngut37/sp02/src/server/api/api.ts
  www/ngut37/sp02/src/server/api/index.ts
  www/ngut37/sp02/src/server/config/config.ts
  www/ngut37/sp02/src/server/config/index.ts
  www/ngut37/sp02/src/styles/_colors.scss
  www/ngut37/sp02/src/styles/_media.scss
  www/ngut37/sp02/src/utils/index.ts
  www/ngut37/sp02/src/utils/status-codes.ts
  www/ngut37/sp02/tsconfig.json
  www/ngut37/sp02/yarn.lock
Labels: Good PR, Jedi knight

#174 podj00-sp2
  www/podj00/sp2/assets/css/styles.css
  www/podj00/sp2/assets/img/covid.png
  www/podj00/sp2/assets/js/main.js
  www/podj00/sp2/assets/js/mockedOneCountry.json
  www/podj00/sp2/assets/js/mockedResponse.json
  www/podj00/sp2/index.html
Labels: Good PR, Jedi knight

#226 beld06 - sp2
  www/beld06/sp2/.gitignore
  www/beld06/sp2/LICENSE
  www/beld06/sp2/css/style.css
  www/beld06/sp2/img/moon.ico
  www/beld06/sp2/index.html
  www/beld06/sp2/js/script.js
Labels: Good PR, Jedi padawan

#238 potp04-sp2
  www/potp04/sp2/css/style.css
  www/potp04/sp2/index.html
  www/potp04/sp2/js/data_cities.js
  www/potp04/sp2/js/main.js
Labels: Good PR

#239 fouf00-sp2
  www/fouf00/sp2/css/styles.css
  www/fouf00/sp2/favicon/android-chrome-192x192.png
  www/fouf00/sp2/favicon/android-chrome-512x512.png
  www/fouf00/sp2/favicon/apple-touch-icon.png
  www/fouf00/sp2/favicon/browserconfig.xml
  www/fouf00/sp2/favicon/favicon-16x16.png
  www/fouf00/sp2/favicon/favicon-32x32.png
  www/fouf00/sp2/favicon/favicon.ico
  www/fouf00/sp2/favicon/mstile-150x150.png
  www/fouf00/sp2/favicon/safari-pinned-tab.svg
  www/fouf00/sp2/favicon/site.webmanifest
  www/fouf00/sp2/index.html
  www/fouf00/sp2/js/app.js
Labels: Good PR

#235 vecs00-sp2
  www/vecs00/sp2/css/bootstrap.min.css
  www/vecs00/sp2/css/main.css
  www/vecs00/sp2/img/favicon.png
  www/vecs00/sp2/index.html
  www/vecs00/sp2/js/main.js
Labels: Good PR, Jedi knight

#183 ruzv01-sp2
  www/ruzv01/sp2/assets/favicon-16x16.png
  www/ruzv01/sp2/assets/favicon-192x192.png
  www/ruzv01/sp2/assets/favicon-32x32.png
  www/ruzv01/sp2/assets/favicon-96x96.png
  www/ruzv01/sp2/index.html
  www/ruzv01/sp2/main.js
Labels: Good PR, Jedi knight

#243 kozo01-sp2
  www/kozo01/sp2/css/style.css
  www/kozo01/sp2/index.html
  www/kozo01/sp2/scripts/app.js
  www/kozo01/sp2/scripts/config.js
Labels: Jedi padawan

#207 klep03-sp2
  www/klep03/sp2/accountManager/index.html
  www/klep03/sp2/css/accountManager.css
  www/klep03/sp2/css/form.css
  www/klep03/sp2/form/index.html
  www/klep03/sp2/index.html
  www/klep03/sp2/js/accountManager.js
  www/klep03/sp2/js/form.js
Labels: Good PR, Jedi knight

#240 pivt02-sp2
  www/pivt02/sp2/img/favicon.ico
  www/pivt02/sp2/img/loading.gif
  www/pivt02/sp2/index.html
  www/pivt02/sp2/js/main.js
  www/pivt02/sp2/styles/style.css
Labels: Jedi padawan

#186 novb12-sp2
  www/novb12/sp2/assets/css/styles.css
  www/novb12/sp2/assets/img/favicon/16.png
  www/novb12/sp2/assets/img/favicon/180.png
  www/novb12/sp2/assets/img/favicon/32.png
  www/novb12/sp2/assets/img/favicon/96.png
  www/novb12/sp2/assets/js/main.js
  www/novb12/sp2/index.html
Labels: Good PR, Jedi padawan

#217 stea11-sp2
  www/stea11/sp2/.prettierrc
  www/stea11/sp2/css/loader.css
  www/stea11/sp2/css/main.css
  www/stea11/sp2/index.html
  www/stea11/sp2/js/api.js
  www/stea11/sp2/js/main.js
Labels: Good PR

#189 doss02-sp2
  www/doss02/sp2/css/main.css
  www/doss02/sp2/img/favicon.png
  www/doss02/sp2/img/image-4.jpg
  www/doss02/sp2/index.html
  www/doss02/sp2/javascript/main.js
  www/doss02/sp2/javaskript/main.js
Labels: Good PR

#209 ulvo00-sp2
  www/ulvo00/sp2/css/main.css
  www/ulvo00/sp2/index.html
  www/ulvo00/sp2/js/main.js
Labels: Good PR

#229 patl03-sp2
  www/patl03/sp2/css/style.css
  www/patl03/sp2/img/index.png
  www/patl03/sp2/img/loading.svg
  www/patl03/sp2/index.html
  www/patl03/sp2/js/main.js
Labels: Good PR

#216 udoy00-sp2
  babel.config.js
  public/favicon.png
  public/index.html
  src/App.vue
  src/assets/logo.png
  src/common-def.scss
  src/components/ItineraryForm.vue
  src/components/Map.vue
  src/main.js
  src/pages/HomePage.vue
  src/router/index.js
  src/service/BackEndMockService.js
  src/service/RouteService.js
  src/store/store.js
  www/udoy00/sp2/README.md
  www/udoy00/sp2/babel.config.js
  www/udoy00/sp2/package-lock.json
  www/udoy00/sp2/package.json
  www/udoy00/sp2/public/favicon.png
  www/udoy00/sp2/public/index.html
  www/udoy00/sp2/sp2.iml
  www/udoy00/sp2/src/App.vue
  www/udoy00/sp2/src/assets/logo.png
  www/udoy00/sp2/src/common-def.scss
  www/udoy00/sp2/src/components/ItineraryForm.vue
  www/udoy00/sp2/src/components/Map.vue
  www/udoy00/sp2/src/main.js
  www/udoy00/sp2/src/pages/HomePage.vue
  www/udoy00/sp2/src/router/index.js
  www/udoy00/sp2/src/service/BackEndMockService.js
  www/udoy00/sp2/src/service/RouteService.js
  www/udoy00/sp2/src/store/store.js
Labels: Good PR

#184 gerv03-sp2
  www/gerv03/sp2/css/main.css
  www/gerv03/sp2/img/favicon.ico
  www/gerv03/sp2/index.html
  www/gerv03/sp2/js/main.js
Labels: Good PR

#210 mrkm00 - sp2
  www/mrkm00/sp2/assets/css/styles.css
  www/mrkm00/sp2/assets/images/favicons/favicon.ico
  www/mrkm00/sp2/assets/images/favicons/instagram+logo+label+logo+icon-1320184017777688375_32.png
  www/mrkm00/sp2/assets/images/favicons/instagram+logo+label+logo+icon-1320184017777688375_64.png
  www/mrkm00/sp2/assets/js/main.js
  www/mrkm00/sp2/index.html
Labels: Good PR

#201 sinj04-sp2
  www/sinj04/sp2/img/background.jpg
  www/sinj04/sp2/img/favicon.ico
  www/sinj04/sp2/index.html
  www/sinj04/sp2/js/index.js
  www/sinj04/sp2/js/jquery-3.5.1.min.js
  www/sinj04/sp2/styles/index.css
Labels: Good PR

#205 toho00-sp2
  www/toho00/sp2/README.md
  www/toho00/sp2/build/asset-manifest.json
  www/toho00/sp2/build/favicon.ico
  www/toho00/sp2/build/index.html
  www/toho00/sp2/build/logo192.png
  www/toho00/sp2/build/logo512.png
  www/toho00/sp2/build/manifest.json
  www/toho00/sp2/build/robots.txt
  www/toho00/sp2/build/static/css/2.b9715c71.chunk.css
  www/toho00/sp2/build/static/css/2.b9715c71.chunk.css.map
  www/toho00/sp2/build/static/css/main.12ad2bf6.chunk.css
  www/toho00/sp2/build/static/css/main.12ad2bf6.chunk.css.map
  www/toho00/sp2/build/static/js/2.94b10e46.chunk.js
  www/toho00/sp2/build/static/js/2.94b10e46.chunk.js.LICENSE.txt
  www/toho00/sp2/build/static/js/2.94b10e46.chunk.js.map
  www/toho00/sp2/build/static/js/3.1e73a4b0.chunk.js
  www/toho00/sp2/build/static/js/3.1e73a4b0.chunk.js.map
  www/toho00/sp2/build/static/js/main.e2336310.chunk.js
  www/toho00/sp2/build/static/js/main.e2336310.chunk.js.map
  www/toho00/sp2/build/static/js/runtime-main.792d5802.js
  www/toho00/sp2/build/static/js/runtime-main.792d5802.js.map
  www/toho00/sp2/build/static/media/equals.4546a346.png
  www/toho00/sp2/build/static/media/exchange.5246d295.png
  www/toho00/sp2/build/static/media/roboto-all-400-normal.b5a0a0df.woff
  www/toho00/sp2/build/static/media/roboto-cyrillic-400-normal.3605d18d.woff2
  www/toho00/sp2/build/static/media/roboto-cyrillic-ext-400-normal.dd55ea0a.woff2
  www/toho00/sp2/build/static/media/roboto-greek-400-normal.352cc77a.woff2
  www/toho00/sp2/build/static/media/roboto-greek-ext-400-normal.bc7ace6e.woff2
  www/toho00/sp2/build/static/media/roboto-latin-400-normal.176f8f5b.woff2
  www/toho00/sp2/build/static/media/roboto-latin-ext-400-normal.dcc07bcf.woff2
  www/toho00/sp2/build/static/media/roboto-vietnamese-400-normal.52cebac0.woff2
  www/toho00/sp2/css/styles.css
  www/toho00/sp2/images/currency-exchange.png
  www/toho00/sp2/images/equals.png
  www/toho00/sp2/images/favicon-16x16.png
  www/toho00/sp2/index.html
  www/toho00/sp2/package-lock.json
  www/toho00/sp2/package.json
  www/toho00/sp2/public/favicon.ico
  www/toho00/sp2/public/index.html
  www/toho00/sp2/public/logo192.png
  www/toho00/sp2/public/logo512.png
  www/toho00/sp2/public/manifest.json
  www/toho00/sp2/public/robots.txt
  www/toho00/sp2/src/App.css
  www/toho00/sp2/src/App.js
  www/toho00/sp2/src/App.test.js
  www/toho00/sp2/src/CurrencyRow.js
  www/toho00/sp2/src/FavCurrencyRow.js
  www/toho00/sp2/src/Img/equals.png
  www/toho00/sp2/src/Img/exchange.png
  www/toho00/sp2/src/Table.js
  www/toho00/sp2/src/index.css
  www/toho00/sp2/src/index.js
  www/toho00/sp2/src/logo.svg
  www/toho00/sp2/src/reportWebVitals.js
  www/toho00/sp2/src/setupTests.js
Labels: Good PR
